'use client'
import { useState, useRef, useEffect, useMemo } from 'react'

const CATEGORIES: { label: string; icon: string; emojis: string[] }[] = [
  { label: 'Common', icon: '⭐', emojis: ['📄','📝','📌','⭐','🔥','💡','🎯','📊','🗂','🌿','🚀','💎','🎨','🔑','📦','🌍','💬','🧠','✅','🎉','🏠','🔧','📚','🎵','🌸','⚡','🦋','🌊','🏔','🎭','📐','🔬','🌈','🍀','🦁','🐋','🌙','☀️','🎪','🏆'] },
  { label: 'Smileys', icon: '😀', emojis: ['😀','😃','😄','😁','😆','😅','🤣','😂','🙂','🙃','😉','😊','😇','🥰','😍','🤩','😘','😗','😚','😙','🥲','😋','😛','😜','🤪','😝','🤑','🤗','🤭','🤫','🤔','🤐','🤨','😐','😑','😶','😏','😒','🙄','😬','🤥','😌','😔','😪','🤤','😴','😷','🤒','🤕','🤢','🤮','🤧','🥵','🥶','🥴','😵','🤯','🤠','🥸','🥳','😎','🤓','🧐','😕','😟','🙁','☹️','😮','😯','😲','😳','🥺','😦','😧','😨','😰','😥','😢','😭','😱','😖','😣','😞','😓','😩','😫','🥱','😤','😡','😠','🤬','😈','👿','💀','☠️','💩','🤡','👹','👺','👻','👽','👾','🤖'] },
  { label: 'People', icon: '👋', emojis: ['👋','🤚','🖐','✋','🖖','👌','🤌','🤏','✌️','🤞','🤟','🤘','🤙','👈','👉','👆','🖕','👇','☝️','👍','👎','✊','👊','🤛','🤜','👏','🙌','👐','🤲','🤝','🙏','✍️','💅','🤳','💪','🦾','🦿','🦵','🦶','👂','🦻','👃','🧠','🫀','🫁','🦷','🦴','👀','👁','👅','👄','🫦','👶','🧒','👦','👧','🧑','👱','👨','🧔','👩','🧓','👴','👵','🙍','🙎','🙅','🙆','💁','🙋','🧏','🙇','🤦','🤷','👮','🕵️','💂','🥷','👷','🤴','👸','👳','👲','🧕','🤵','👰','🤰','🤱','👼','🎅','🤶','🦸','🦹','🧙','🧚','🧛','🧜','🧝','🧞','🧟','🧌','💆','💇','🚶','🧍','🧎','🏃','💃','🕺','🕴','👯','🧖','🧗','🤺','🏇','⛷','🏂','🪂','🏋','🤼','🤸','🤽','🤾','🤹','🧘','🛀','🛌','🧑‍🤝‍🧑','👫','👬','👭','💏','💑','👪'] },
  { label: 'Animals', icon: '🐶', emojis: ['🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐻‍❄️','🐨','🐯','🦁','🐮','🐷','🐸','🐵','🙈','🙉','🙊','🐔','🐧','🐦','🐤','🦆','🦅','🦉','🦇','🐺','🐗','🐴','🦄','🐝','🪱','🐛','🦋','🐌','🐞','🐜','🪲','🦟','🦗','🪳','🦂','🐢','🐍','🦎','🦖','🦕','🐙','🦑','🦐','🦞','🦀','🐡','🐠','🐟','🐬','🐳','🐋','🦈','🐊','🐅','🐆','🦓','🦍','🦧','🦣','🐘','🦛','🦏','🐪','🐫','🦒','🦘','🦬','🐃','🐂','🐄','🐎','🐖','🐏','🐑','🦙','🐐','🦌','🐕','🐩','🦮','🐈','🐓','🦃','🦤','🦚','🦜','🦢','🦩','🕊','🐇','🦝','🦨','🦡','🦫','🦦','🦥','🐁','🐀','🐿','🦔'] },
  { label: 'Food', icon: '🍕', emojis: ['🍏','🍎','🍐','🍊','🍋','🍌','🍉','🍇','🍓','🫐','🍈','🍒','🍑','🥭','🍍','🥥','🥝','🍅','🍆','🥑','🥦','🫛','🥬','🥒','🌶','🫑','🧄','🧅','🥔','🍠','🫚','🥐','🥯','🍞','🥖','🥨','🧀','🥚','🍳','🧈','🥞','🧇','🥓','🥩','🍗','🍖','🦴','🌭','🍔','🍟','🍕','🫓','🥪','🥙','🧆','🌮','🌯','🫔','🥗','🥘','🫕','🥫','🍝','🍜','🍲','🍛','🍣','🍱','🥟','🦪','🍤','🍙','🍚','🍘','🍥','🥮','🍢','🧁','🍰','🎂','🍮','🍭','🍬','🍫','🍿','🍩','🍪','🌰','🥜','🍯','🧃','🥤','🧋','☕','🫖','🍵','🧉','🍺','🍻','🥂','🍷','🫗','🥃','🍸','🍹','🧊','🥄','🍴','🫙'] },
  { label: 'Travel', icon: '✈️', emojis: ['🚀','🛸','🚁','🛶','⛵','🚤','🛥','🛳','⛴','🚢','✈️','🛩','🛫','🛬','🪂','💺','🚂','🚃','🚄','🚅','🚆','🚇','🚈','🚉','🚊','🚝','🚞','🚋','🚌','🚍','🚎','🚐','🚑','🚒','🚓','🚔','🚕','🚖','🚗','🚘','🚙','🛻','🚚','🚛','🚜','🏎','🏍','🛵','🦽','🦼','🛺','🚲','🛴','🛹','🛼','🚏','🛣','🛤','⛽','🛞','🚨','🚥','🚦','🛑','🚧','⚓','🪝','⛵','🚣','🛶','🏊','🧗','🏌','🏇','🤸','⛷','🏋','🤼','🤺','🛹','🏄','🚵','🏆','🥇','🥈','🥉','🏅','🎖','🎗','🎫','🎟','🎪','🎭','🎨','🖼','🎰','🎲','♟','🧩','🎮','🕹','🎯','🎳','🎻','🎺','🥁','🪘','🎸','🪕','🎷','🎹','🎵','🎶','🎤','🎧','📻','🎙','📢','📣'] },
  { label: 'Objects', icon: '💼', emojis: ['💼','📁','📂','🗂','📋','📊','📈','📉','🗒','🗓','📆','📅','🗑','📇','📌','📍','✂️','🖇','📎','🔗','📏','📐','✒️','🖋','✏️','🖊','🖌','🖍','📝','🔍','🔎','🔏','🔐','🔒','🔓','🔑','🗝','🔨','🪓','⛏','⚒','🛠','🗡','⚔️','🛡','🔧','🔩','⚙️','🗜','⚖️','🦯','🔗','⛓','🪝','🧰','🧲','🪜','⚗️','🧪','🧫','🧬','🔭','🔬','🩺','💊','🩹','🩼','🩻','🚪','🛋','🪑','🚿','🛁','🧴','🧷','🧹','🧺','🧻','🪣','🧼','🫧','🪥','🧽','🪒','🧯','🪤','🛒','💡','🔦','🕯','🪔','🧱','🪞','🖥','🖨','⌨️','🖱','🖲','💾','💿','📀','📼','📷','📸','📹','🎥','📽','🎞','📞','☎️','📟','📠','📺','📻','🧭','⏱','⏲','⏰','🕰','⌛','⏳','📡','🔋','🪫','🔌','💻','📱','📲','💬','📩','📨','📧','📫','📪','📬','📭','📮','🗳','✏️','📏','📌','🗺','🌐'] },
  { label: 'Symbols', icon: '❤️', emojis: ['❤️','🧡','💛','💚','💙','💜','🖤','🤍','🤎','💔','❣️','💕','💞','💓','💗','💖','💘','💝','💟','☮️','✝️','☪️','🕉','☯️','✡️','🔯','🕎','☦️','⛎','♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓','🆔','⚛️','🉑','☢️','☣️','📴','📳','🈶','🈚','🈸','🈺','🈷️','✴️','🆚','💮','🉐','㊙️','㊗️','🈴','🈵','🈹','🈲','🅰️','🅱️','🆎','🆑','🅾️','🆘','❌','⭕','🛑','⛔','📛','🚫','💯','💢','♨️','🚷','🚯','🚳','🚱','🔞','📵','🚭','❗','❕','❓','❔','‼️','⁉️','🔅','🔆','〽️','⚠️','🚸','🔱','⚜️','🔰','♻️','✅','🈯','💹','❎','🌐','💠','Ⓜ️','🌀','💤','🏧','🚾','♿','🅿️','🛗','🈳','🈂️','🛂','🛃','🛄','🛅','🚹','🚺','🚼','⚧️','🚻','🚮','🎦','📶','🈁','🔣','ℹ️','🔤','🔡','🔠','🆖','🆗','🆙','🆒','🆕','🆓','0️⃣','1️⃣','2️⃣','3️⃣','4️⃣','5️⃣','6️⃣','7️⃣','8️⃣','9️⃣','🔟','🔢','⏏️','▶️','⏸','⏹','⏺','⏭','⏮','⏩','⏪','⏫','⏬','◀️','🔼','🔽','➡️','⬅️','⬆️','⬇️','↗️','↘️','↙️','↖️','↕️','↔️','↪️','↩️','⤴️','⤵️','🔀','🔁','🔂','🔄','🔃','🎵','🎶','➕','➖','➗','✖️','♾️','💲','💱','™️','©️','®️','〰️','➰','➿','🔚','🔙','🔛','🔝','🔜','✔️','☑️','🔘','🔴','🟠','🟡','🟢','🔵','🟣','⚫','⚪','🟤','🔺','🔻','🔷','🔶','🔹','🔸','🔳','🔲','▪️','▫️','◾','◽','◼️','◻️','🟥','🟧','🟨','🟩','🟦','🟪','⬛','⬜','🟫','🔈','🔇','🔉','🔊','🔔','🔕','📣','📢','💬','💭','🗯','♠️','♣️','♥️','♦️','🃏','🀄','🎴'] },
]

const EMOJI_KW: Record<string, string> = {
  // Common
  '📄': 'document page file paper',
  '📝': 'memo note write pencil edit',
  '📌': 'pin pushpin bookmark',
  '⭐': 'star favorite starred',
  '🔥': 'fire hot flame trending',
  '💡': 'lightbulb idea light',
  '🎯': 'target dart goal aim bullseye',
  '📊': 'bar chart graph data statistics',
  '🗂': 'card index folder organize tabs',
  '🌿': 'herb leaf plant nature green',
  '🚀': 'rocket launch space fast',
  '💎': 'diamond gem jewel crystal',
  '🎨': 'palette art paint creative design',
  '🔑': 'key password lock unlock',
  '📦': 'package box shipping delivery',
  '🌍': 'earth globe world europe africa',
  '💬': 'speech bubble comment chat talk message',
  '🧠': 'brain mind think intelligence smart',
  '✅': 'check mark done complete task tick',
  '🎉': 'party tada celebration confetti',
  '🏠': 'house home building',
  '🔧': 'wrench spanner tool fix repair',
  '📚': 'books library study read',
  '🎵': 'music note song melody',
  '🌸': 'cherry blossom flower pink spring',
  '⚡': 'lightning bolt electric energy fast zap',
  '🦋': 'butterfly nature transform',
  '🌊': 'wave ocean sea water surf',
  '🏔': 'mountain snow peak landscape',
  '🎭': 'theater drama performing arts masks',
  '📐': 'ruler triangle geometry measure',
  '🔬': 'microscope science lab research biology',
  '🌈': 'rainbow colors colorful',
  '🍀': 'clover luck lucky four leaf',
  '🦁': 'lion animal king',
  '🐋': 'whale ocean sea animal',
  '🌙': 'crescent moon night',
  '☀️': 'sun sunny weather daylight',
  '🎪': 'circus tent show performance',
  '🏆': 'trophy winner award cup champion',
  // Smileys
  '😀': 'grinning smile happy face',
  '😃': 'happy smile big eyes face',
  '😄': 'grin smile happy face',
  '😁': 'beaming smile grin face',
  '😆': 'laughing grin haha face',
  '😅': 'sweat smile nervous awkward face',
  '🤣': 'rolling floor laughing rofl face',
  '😂': 'tears joy laugh crying face',
  '🙂': 'slightly smiling face',
  '🙃': 'upside down face',
  '😉': 'wink winking face',
  '😊': 'smiling blushing happy face',
  '😇': 'angel innocent halo face',
  '🥰': 'smiling hearts love adore face',
  '😍': 'heart eyes love adore face',
  '🤩': 'star struck wow amazing face',
  '😘': 'blowing kiss face',
  '😗': 'kissing face',
  '😚': 'kissing closed eyes face',
  '😙': 'kissing smiling eyes face',
  '🥲': 'smiling tear sad happy face',
  '😋': 'yum delicious food tongue face',
  '😛': 'tongue face',
  '😜': 'winking tongue face',
  '🤪': 'zany crazy face',
  '😝': 'squinting tongue face',
  '🤑': 'money mouth rich face',
  '🤗': 'hugging hug face',
  '🤭': 'hand covering mouth face',
  '🤫': 'shushing quiet silent face',
  '🤔': 'thinking hmm wonder face',
  '🤐': 'zipper mouth silent face',
  '🤨': 'raised eyebrow skeptical suspicious face',
  '😐': 'neutral meh face',
  '😑': 'expressionless blank face',
  '😶': 'no mouth silent face',
  '😏': 'smirking smug face',
  '😒': 'unamused unhappy face',
  '🙄': 'eye roll face',
  '😬': 'grimacing teeth awkward face',
  '🤥': 'lying pinocchio face',
  '😌': 'relieved calm peaceful face',
  '😔': 'pensive sad thoughtful face',
  '😪': 'sleepy tired face',
  '🤤': 'drooling face',
  '😴': 'sleeping zzz tired face',
  '😷': 'mask sick ill face',
  '🤒': 'thermometer sick fever ill face',
  '🤕': 'bandage hurt injured face',
  '🤢': 'nauseated sick green face',
  '🤮': 'vomiting sick disgusted face',
  '🤧': 'sneezing cold sick tissue face',
  '🥵': 'hot face sweating overheated',
  '🥶': 'cold face freezing',
  '🥴': 'woozy drunk dizzy face',
  '😵': 'dizzy knocked out face',
  '🤯': 'exploding head shocked mind blown face',
  '🤠': 'cowboy hat western face',
  '🥸': 'disguised glasses face',
  '🥳': 'partying celebration birthday face',
  '😎': 'sunglasses cool confident face',
  '🤓': 'nerd glasses study face',
  '🧐': 'monocle curious examine face',
  '😕': 'confused face',
  '😟': 'worried face',
  '🙁': 'frowning sad face',
  '☹️': 'frowning sad face',
  '😮': 'open mouth surprised face',
  '😯': 'hushed surprised face',
  '😲': 'astonished shocked face',
  '😳': 'flushed embarrassed face',
  '🥺': 'pleading puppy eyes face',
  '😦': 'frowning open mouth face',
  '😧': 'anguished worried face',
  '😨': 'fearful scared face',
  '😰': 'anxious cold sweat face',
  '😥': 'sad relieved sweat face',
  '😢': 'crying sad tear face',
  '😭': 'loudly crying sob face',
  '😱': 'screaming fear horror face',
  '😖': 'confounded frustrated face',
  '😣': 'persevering struggling face',
  '😞': 'disappointed sad face',
  '😓': 'downcast sweat face',
  '😩': 'weary tired face',
  '😫': 'tired exhausted face',
  '🥱': 'yawning bored sleepy face',
  '😤': 'huffing triumph angry face',
  '😡': 'pouting angry red face',
  '😠': 'angry mad face',
  '🤬': 'cursing swearing angry symbols face',
  '😈': 'devil smiling evil face',
  '👿': 'angry devil evil face',
  '💀': 'skull death dead bones',
  '☠️': 'skull crossbones death danger',
  '💩': 'pile poop shit funny',
  '🤡': 'clown joke funny face',
  '👹': 'ogre demon monster',
  '👺': 'goblin red monster',
  '👻': 'ghost spooky halloween',
  '👽': 'alien space extraterrestrial',
  '👾': 'alien monster game robot space',
  '🤖': 'robot machine android ai',
  // People / Hands
  '👋': 'waving hand hello bye wave',
  '🤚': 'raised back hand stop',
  '🖐': 'hand raised fingers spread',
  '✋': 'raised hand stop high five',
  '🖖': 'vulcan salute spock',
  '👌': 'ok hand perfect',
  '🤌': 'pinched fingers italian',
  '🤏': 'pinching hand small',
  '✌️': 'victory peace sign fingers',
  '🤞': 'fingers crossed luck hope',
  '🤟': 'love you gesture sign',
  '🤘': 'rock on horns metal sign',
  '🤙': 'call me shaka hang loose',
  '👈': 'pointing left backhand index',
  '👉': 'pointing right backhand index',
  '👆': 'pointing up backhand index',
  '🖕': 'middle finger rude',
  '👇': 'pointing down backhand index',
  '☝️': 'pointing up index finger',
  '👍': 'thumbs up like approve good yes',
  '👎': 'thumbs down dislike bad no',
  '✊': 'raised fist power',
  '👊': 'oncoming fist punch',
  '🤛': 'left fist bump',
  '🤜': 'right fist bump',
  '👏': 'clapping hands applause',
  '🙌': 'raising hands celebration praise',
  '👐': 'open hands hug',
  '🤲': 'palms together prayer',
  '🤝': 'handshake deal agreement',
  '🙏': 'folded hands please thank you prayer',
  '✍️': 'writing hand pen sign',
  '💅': 'nail polish manicure nails',
  '🤳': 'selfie phone camera',
  '💪': 'flexed biceps strong muscle arm',
  '🦾': 'mechanical arm prosthetic',
  '🦿': 'mechanical leg prosthetic',
  '🦵': 'leg kick',
  '🦶': 'foot kick',
  '👂': 'ear listen hear',
  '🦻': 'ear hearing aid',
  '👃': 'nose smell',
  '🧠': 'brain mind think intelligence',
  '🫀': 'anatomical heart organ',
  '🫁': 'lungs breathing organ',
  '🦷': 'tooth teeth dental',
  '🦴': 'bone skeleton',
  '👀': 'eyes look see watch',
  '👁': 'eye watch see',
  '👅': 'tongue taste lick',
  '👄': 'mouth lips kiss',
  '🫦': 'biting lip',
  '👶': 'baby infant',
  '🧒': 'child kid',
  '👦': 'boy',
  '👧': 'girl',
  '🧑': 'person adult',
  '👱': 'blonde person',
  '👨': 'man person',
  '🧔': 'person beard',
  '👩': 'woman person',
  '🧓': 'older person',
  '👴': 'old man elderly grandfather',
  '👵': 'old woman elderly grandmother',
  '🙍': 'frowning person',
  '🙎': 'pouting person',
  '🙅': 'no gesture person',
  '🙆': 'ok gesture person',
  '💁': 'tipping hand sassy person',
  '🙋': 'raising hand person',
  '🧏': 'deaf person sign language',
  '🙇': 'bowing person',
  '🤦': 'facepalm person',
  '🤷': 'shrug person',
  '👮': 'police officer cop',
  '🕵️': 'detective spy investigate',
  '💂': 'guard soldier',
  '🥷': 'ninja stealth',
  '👷': 'construction worker hard hat build',
  '🤴': 'prince royalty',
  '👸': 'princess royalty',
  '👳': 'turban person',
  '👲': 'skullcap person',
  '🧕': 'headscarf person',
  '🤵': 'suit tuxedo formal wedding',
  '👰': 'wedding veil bride',
  '🤰': 'pregnant woman',
  '🤱': 'breastfeeding baby mother',
  '👼': 'baby angel',
  '🎅': 'santa christmas',
  '🤶': 'mrs santa christmas',
  '🦸': 'superhero',
  '🦹': 'supervillain',
  '🧙': 'mage wizard magic',
  '🧚': 'fairy magic',
  '🧛': 'vampire',
  '🧜': 'mermaid merman',
  '🧝': 'elf',
  '🧞': 'genie djinn lamp',
  '🧟': 'zombie undead',
  '🧌': 'troll',
  '💆': 'massage person relax',
  '💇': 'haircut person barber',
  '🚶': 'walking person walk',
  '🧍': 'standing person',
  '🧎': 'kneeling person',
  '🏃': 'running person sprint run',
  '💃': 'dancing woman',
  '🕺': 'dancing man',
  '🕴': 'suit levitate',
  '👯': 'bunny ears dancing',
  '🧖': 'sauna steam person relax',
  '🧗': 'climbing person rock',
  '🤺': 'fencing sword sport',
  '🏇': 'horse racing jockey',
  '⛷': 'skiing person snow',
  '🏂': 'snowboarding person snow',
  '🪂': 'parachute skydiving jump',
  '🏋': 'weight lifting gym strong',
  '🤼': 'wrestling sport',
  '🤸': 'gymnastics cartwheel flip',
  '🤽': 'water polo swim',
  '🤾': 'handball sport',
  '🤹': 'juggling circus',
  '🧘': 'yoga meditation lotus calm',
  '🛀': 'bath bathtub relax',
  '🛌': 'sleeping person bed rest',
  '🧑‍🤝‍🧑': 'people holding hands couple friends',
  '👫': 'couple man woman',
  '👬': 'couple two men',
  '👭': 'couple two women',
  '💏': 'kiss couple romance',
  '💑': 'couple heart love',
  '👪': 'family parents children',
  // Animals
  '🐶': 'dog puppy pet',
  '🐱': 'cat kitten pet',
  '🐭': 'mouse rodent',
  '🐹': 'hamster pet',
  '🐰': 'rabbit bunny',
  '🦊': 'fox animal',
  '🐻': 'bear animal',
  '🐼': 'panda bear bamboo',
  '🐻‍❄️': 'polar bear ice arctic',
  '🐨': 'koala bear australia',
  '🐯': 'tiger stripes',
  '🦁': 'lion king mane',
  '🐮': 'cow moo farm',
  '🐷': 'pig oink farm',
  '🐸': 'frog green leap',
  '🐵': 'monkey face primate',
  '🙈': 'see no evil monkey',
  '🙉': 'hear no evil monkey',
  '🙊': 'speak no evil monkey',
  '🐔': 'chicken hen farm bird',
  '🐧': 'penguin bird arctic',
  '🐦': 'bird',
  '🐤': 'baby chick chicken',
  '🦆': 'duck quack bird',
  '🦅': 'eagle bird raptor',
  '🦉': 'owl bird night',
  '🦇': 'bat night halloween',
  '🐺': 'wolf howl',
  '🐗': 'boar pig wild',
  '🐴': 'horse neigh',
  '🦄': 'unicorn magic rainbow horse',
  '🐝': 'honeybee bee buzz',
  '🪱': 'worm earth',
  '🐛': 'bug caterpillar worm',
  '🦋': 'butterfly transform wings',
  '🐌': 'snail slow shell',
  '🐞': 'ladybug beetle red',
  '🐜': 'ant insect',
  '🪲': 'beetle bug insect',
  '🦟': 'mosquito insect bite',
  '🦗': 'cricket grasshopper insect',
  '🪳': 'cockroach bug insect',
  '🦂': 'scorpion desert',
  '🐢': 'turtle slow shell',
  '🐍': 'snake reptile',
  '🦎': 'lizard reptile',
  '🦖': 'dinosaur t-rex trex',
  '🦕': 'dinosaur sauropod brachiosaurus',
  '🐙': 'octopus tentacles sea',
  '🦑': 'squid sea tentacles',
  '🦐': 'shrimp seafood',
  '🦞': 'lobster seafood',
  '🦀': 'crab seafood beach',
  '🐡': 'blowfish puffer sea',
  '🐠': 'tropical fish sea',
  '🐟': 'fish sea',
  '🐬': 'dolphin sea swim',
  '🐳': 'whale spouting sea',
  '🐋': 'whale sea ocean',
  '🦈': 'shark sea fish',
  '🐊': 'crocodile alligator reptile',
  '🐅': 'tiger stripes cat',
  '🐆': 'leopard spots cat',
  '🦓': 'zebra stripes',
  '🦍': 'gorilla ape primate',
  '🦧': 'orangutan ape primate',
  '🦣': 'mammoth elephant prehistoric',
  '🐘': 'elephant trunk safari',
  '🦛': 'hippopotamus hippo',
  '🦏': 'rhinoceros rhino horn',
  '🐪': 'camel one hump desert',
  '🐫': 'bactrian camel two humps',
  '🦒': 'giraffe tall neck safari',
  '🦘': 'kangaroo australia jump',
  '🦬': 'bison buffalo',
  '🐃': 'water buffalo',
  '🐂': 'ox bull farm',
  '🐄': 'cow farm milk',
  '🐎': 'horse racing',
  '🐖': 'pig farm',
  '🐏': 'ram sheep male',
  '🐑': 'sheep ewe wool',
  '🦙': 'llama alpaca south america',
  '🐐': 'goat farm',
  '🦌': 'deer antlers',
  '🐕': 'dog pet',
  '🐩': 'poodle dog pet',
  '🦮': 'guide dog service',
  '🐈': 'cat pet',
  '🐓': 'rooster cock farm',
  '🦃': 'turkey thanksgiving bird',
  '🦤': 'dodo bird extinct',
  '🦚': 'peacock bird colorful',
  '🦜': 'parrot bird colorful speak',
  '🦢': 'swan bird elegant lake',
  '🦩': 'flamingo pink bird',
  '🕊': 'dove peace bird',
  '🐇': 'rabbit bunny white',
  '🦝': 'raccoon animal',
  '🦨': 'skunk smell animal',
  '🦡': 'badger animal',
  '🦫': 'beaver dam animal',
  '🦦': 'otter sea animal',
  '🦥': 'sloth slow animal',
  '🐁': 'mouse white rodent',
  '🐀': 'rat rodent',
  '🐿': 'chipmunk squirrel',
  '🦔': 'hedgehog spiky',
  // Food
  '🍏': 'green apple fruit',
  '🍎': 'red apple fruit',
  '🍐': 'pear fruit',
  '🍊': 'orange tangerine fruit',
  '🍋': 'lemon citrus fruit sour',
  '🍌': 'banana fruit yellow',
  '🍉': 'watermelon fruit summer',
  '🍇': 'grapes fruit purple',
  '🍓': 'strawberry fruit red',
  '🫐': 'blueberries fruit',
  '🍈': 'melon fruit',
  '🍒': 'cherries fruit red',
  '🍑': 'peach fruit',
  '🥭': 'mango fruit tropical',
  '🍍': 'pineapple tropical fruit',
  '🥥': 'coconut tropical',
  '🥝': 'kiwi fruit green',
  '🍅': 'tomato red vegetable',
  '🍆': 'eggplant aubergine purple vegetable',
  '🥑': 'avocado green healthy',
  '🥦': 'broccoli green vegetable',
  '🫛': 'pea pod vegetable green',
  '🥬': 'leafy greens lettuce vegetable',
  '🥒': 'cucumber green vegetable',
  '🌶': 'hot pepper spicy chili red',
  '🫑': 'bell pepper vegetable',
  '🧄': 'garlic cooking',
  '🧅': 'onion cooking',
  '🥔': 'potato vegetable',
  '🍠': 'sweet potato roasted',
  '🫚': 'olive oil cooking',
  '🥐': 'croissant french pastry bread',
  '🥯': 'bagel bread',
  '🍞': 'bread loaf',
  '🥖': 'baguette french bread',
  '🥨': 'pretzel bread',
  '🧀': 'cheese dairy',
  '🥚': 'egg breakfast',
  '🍳': 'cooking egg frying pan',
  '🧈': 'butter dairy',
  '🥞': 'pancakes breakfast stack',
  '🧇': 'waffle breakfast',
  '🥓': 'bacon breakfast meat',
  '🥩': 'steak meat cut',
  '🍗': 'chicken leg poultry',
  '🍖': 'meat bone',
  '🌭': 'hotdog sausage',
  '🍔': 'hamburger burger fast food',
  '🍟': 'french fries fast food',
  '🍕': 'pizza slice italian',
  '🫓': 'flatbread',
  '🥪': 'sandwich lunch',
  '🥙': 'pita wrap',
  '🧆': 'falafel middle eastern',
  '🌮': 'taco mexican',
  '🌯': 'burrito wrap mexican',
  '🫔': 'tamale mexican',
  '🥗': 'salad green healthy',
  '🥘': 'paella pan rice',
  '🫕': 'fondue pot',
  '🥫': 'canned food',
  '🍝': 'spaghetti pasta italian',
  '🍜': 'noodles ramen asian',
  '🍲': 'pot stew soup',
  '🍛': 'curry rice indian',
  '🍣': 'sushi japanese',
  '🍱': 'bento box japanese',
  '🥟': 'dumpling gyoza chinese',
  '🦪': 'oyster seafood',
  '🍤': 'fried shrimp seafood',
  '🍙': 'rice ball onigiri japanese',
  '🍚': 'cooked rice',
  '🍘': 'rice cracker japanese',
  '🍥': 'fish cake japanese',
  '🥮': 'moon cake chinese',
  '🍢': 'oden japanese',
  '🧁': 'cupcake cake dessert',
  '🍰': 'cake shortcake slice dessert',
  '🎂': 'birthday cake celebrate',
  '🍮': 'custard flan pudding dessert',
  '🍭': 'lollipop candy sweet',
  '🍬': 'candy sweet',
  '🍫': 'chocolate bar sweet',
  '🍿': 'popcorn movie snack',
  '🍩': 'doughnut donut sweet',
  '🍪': 'cookie biscuit sweet',
  '🌰': 'chestnut nut',
  '🥜': 'peanuts nuts',
  '🍯': 'honey jar sweet',
  '🧃': 'juice box drink',
  '🥤': 'cup straw cold drink',
  '🧋': 'bubble tea boba drink',
  '☕': 'coffee hot drink cafe espresso',
  '🫖': 'teapot tea',
  '🍵': 'hot tea beverage',
  '🧉': 'mate drink',
  '🍺': 'beer mug drink',
  '🍻': 'clinking beers celebrate drink',
  '🥂': 'champagne glasses toast celebrate',
  '🍷': 'wine glass red drink',
  '🫗': 'pouring drink',
  '🥃': 'tumbler whisky drink glass',
  '🍸': 'cocktail martini drink',
  '🍹': 'tropical cocktail drink',
  '🧊': 'ice cube cold',
  '🥄': 'spoon utensil',
  '🍴': 'fork knife utensil cutlery',
  '🫙': 'jar container',
  // Travel
  '🛸': 'flying saucer ufo alien space',
  '🚁': 'helicopter fly',
  '🛶': 'canoe boat paddle',
  '⛵': 'sailboat sail boat',
  '🚤': 'speedboat motorboat',
  '🛥': 'motor boat',
  '🛳': 'cruise ship large',
  '⛴': 'ferry boat transport',
  '🚢': 'ship cruise ocean',
  '✈️': 'airplane plane flight travel fly',
  '🛩': 'small airplane private jet',
  '🛫': 'airplane departure takeoff',
  '🛬': 'airplane arrival landing',
  '💺': 'seat airplane chair',
  '🚂': 'locomotive train steam engine',
  '🚃': 'railway car train',
  '🚄': 'high speed train shinkansen bullet',
  '🚅': 'bullet train fast',
  '🚆': 'train railway',
  '🚇': 'metro subway underground tube',
  '🚈': 'light rail train',
  '🚉': 'station train',
  '🚊': 'tram streetcar',
  '🚝': 'monorail train',
  '🚞': 'mountain railway train',
  '🚋': 'tram car',
  '🚌': 'bus transport',
  '🚍': 'oncoming bus',
  '🚎': 'trolleybus',
  '🚐': 'minibus van',
  '🚑': 'ambulance emergency medical',
  '🚒': 'fire truck emergency',
  '🚓': 'police car',
  '🚔': 'oncoming police car',
  '🚕': 'taxi cab',
  '🚖': 'oncoming taxi',
  '🚗': 'car automobile vehicle',
  '🚘': 'oncoming automobile car',
  '🚙': 'suv car vehicle',
  '🛻': 'pickup truck',
  '🚚': 'delivery truck shipping',
  '🚛': 'articulated truck',
  '🚜': 'tractor farm',
  '🏎': 'racing car formula sport',
  '🏍': 'motorcycle bike',
  '🛵': 'scooter moped',
  '🦽': 'manual wheelchair',
  '🦼': 'motorized wheelchair',
  '🛺': 'auto rickshaw tuk tuk',
  '🚲': 'bicycle bike cycle',
  '🛴': 'kick scooter',
  '🛹': 'skateboard',
  '🛼': 'roller skate',
  '🚏': 'bus stop sign',
  '🛣': 'motorway highway road',
  '🛤': 'railway track rail',
  '⛽': 'fuel pump gas station',
  '🛞': 'wheel tire',
  '🚨': 'siren emergency police alert',
  '🚥': 'traffic light signal',
  '🚦': 'vertical traffic light signal',
  '🛑': 'stop sign octagon red',
  '🚧': 'construction barrier warning',
  '⚓': 'anchor ship maritime',
  '🪝': 'hook fishing',
  '🚣': 'rowing boat person',
  '🏊': 'swimming person swim',
  '🏌': 'golf person',
  '🏄': 'surfing person wave',
  '🚵': 'mountain biking person',
  '🥇': 'gold medal first winner',
  '🥈': 'silver medal second',
  '🥉': 'bronze medal third',
  '🏅': 'sports medal award',
  '🎖': 'military medal award',
  '🎗': 'reminder ribbon awareness',
  '🎫': 'ticket event entry',
  '🎟': 'admission ticket event',
  '🖼': 'picture frame painting art',
  '🎰': 'slot machine casino gambling',
  '🎲': 'dice game roll board',
  '♟': 'chess piece board game',
  '🧩': 'puzzle jigsaw piece',
  '🎮': 'video game controller play',
  '🕹': 'joystick game retro',
  '🎳': 'bowling ball pins',
  '🎻': 'violin fiddle instrument',
  '🎺': 'trumpet instrument brass',
  '🥁': 'drum percussion instrument',
  '🪘': 'long drum percussion',
  '🎸': 'guitar electric instrument',
  '🪕': 'banjo instrument',
  '🎷': 'saxophone sax instrument',
  '🎹': 'piano keyboard music instrument',
  '🎶': 'musical notes music songs',
  '🎤': 'microphone sing perform',
  '🎧': 'headphones music listen',
  '📻': 'radio music broadcast',
  '🎙': 'studio microphone podcast record',
  '📢': 'loudspeaker announcement',
  '📣': 'megaphone cheer loud',
  // Objects
  '💼': 'briefcase work business job',
  '📁': 'file folder',
  '📂': 'open file folder',
  '📋': 'clipboard list',
  '📈': 'chart increasing growth trend up',
  '📉': 'chart decreasing decline trend down',
  '🗒': 'spiral notepad notes',
  '🗓': 'spiral calendar date',
  '📆': 'tear off calendar date',
  '📅': 'calendar date',
  '🗑': 'wastebasket trash delete bin',
  '📇': 'card index rolodex',
  '📍': 'round pushpin location map',
  '✂️': 'scissors cut craft',
  '🖇': 'linked paperclips attach',
  '📎': 'paperclip attach',
  '🔗': 'link chain url',
  '📏': 'straight ruler measure length',
  '✒️': 'black nib pen write ink',
  '🖋': 'fountain pen write ink',
  '✏️': 'pencil write edit draw',
  '🖊': 'pen write ink',
  '🖌': 'paintbrush art paint',
  '🖍': 'crayon color draw',
  '🔍': 'magnifying glass search zoom find',
  '🔎': 'magnifying glass search zoom',
  '🔏': 'locked pen',
  '🔐': 'locked key secure',
  '🔒': 'locked padlock secure',
  '🔓': 'unlocked padlock open',
  '🗝': 'old key',
  '🔨': 'hammer tool build',
  '🪓': 'axe chop cut wood',
  '⛏': 'pick mining',
  '⚒': 'hammer pick tools',
  '🛠': 'hammer wrench tools build',
  '🗡': 'dagger sword weapon',
  '⚔️': 'crossed swords fight battle',
  '🛡': 'shield protect defense',
  '🔩': 'nut bolt screw fastener',
  '⚙️': 'gear settings cog',
  '🗜': 'clamp compression',
  '⚖️': 'scales balance justice law',
  '🦯': 'probing cane blind',
  '⛓': 'chains link',
  '🧰': 'toolbox tools kit',
  '🧲': 'magnet attract pull',
  '🪜': 'ladder climb step',
  '⚗️': 'alembic chemistry flask',
  '🧪': 'test tube lab experiment science',
  '🧫': 'petri dish lab science biology',
  '🧬': 'dna genetics biology science',
  '🔭': 'telescope astronomy space stars',
  '🩺': 'stethoscope doctor medical health',
  '💊': 'pill medicine drug',
  '🩹': 'bandage adhesive wound',
  '🩼': 'crutch medical',
  '🩻': 'x-ray medical scan',
  '🚪': 'door entrance open close',
  '🛋': 'couch sofa furniture',
  '🪑': 'chair seat furniture',
  '🚿': 'shower bath clean',
  '🛁': 'bathtub bath relax',
  '🧴': 'lotion bottle soap hygiene',
  '🧷': 'safety pin sewing',
  '🧹': 'broom sweep clean',
  '🧺': 'basket laundry wicker',
  '🧻': 'roll paper toilet tissue',
  '🪣': 'bucket pail water',
  '🧼': 'soap clean wash hygiene',
  '🫧': 'bubbles soap clean',
  '🪥': 'toothbrush teeth clean dental',
  '🧽': 'sponge clean scrub',
  '🪒': 'razor shave blade',
  '🧯': 'fire extinguisher safety',
  '🪤': 'mouse trap',
  '🛒': 'shopping cart trolley buy',
  '🔦': 'flashlight torch light',
  '🕯': 'candle light flame wax',
  '🪔': 'diya oil lamp light',
  '🧱': 'brick wall build construction',
  '🪞': 'mirror reflection',
  '🖥': 'desktop computer screen monitor',
  '🖨': 'printer print',
  '⌨️': 'keyboard type computer',
  '🖱': 'computer mouse click',
  '🖲': 'trackball computer',
  '💾': 'floppy disk save storage',
  '💿': 'optical disc cd music',
  '📀': 'dvd disc video',
  '📼': 'videocassette vhs tape',
  '📷': 'camera photo picture',
  '📸': 'camera flash photo selfie',
  '📹': 'video camera film record',
  '🎥': 'movie camera film cinema',
  '📽': 'film projector cinema',
  '🎞': 'film strip cinema',
  '📞': 'telephone receiver call phone',
  '☎️': 'telephone call landline',
  '📟': 'pager beeper',
  '📠': 'fax machine send',
  '📺': 'television tv screen',
  '🧭': 'compass navigation direction',
  '⏱': 'stopwatch timer sport',
  '⏲': 'timer clock countdown',
  '⏰': 'alarm clock wake',
  '🕰': 'mantelpiece clock',
  '⌛': 'hourglass done time',
  '⏳': 'hourglass time counting',
  '📡': 'satellite antenna signal',
  '🔋': 'battery power charge energy',
  '🪫': 'low battery dead',
  '🔌': 'electric plug power outlet',
  '💻': 'laptop computer portable',
  '📱': 'mobile phone smartphone',
  '📲': 'mobile phone arrow call',
  '📩': 'envelope arrow email incoming',
  '📨': 'incoming envelope email',
  '📧': 'email letter',
  '📫': 'closed mailbox post',
  '📪': 'open mailbox post empty',
  '📬': 'open mailbox mail raised flag',
  '📭': 'open mailbox empty lowered',
  '📮': 'postbox mail red',
  '🗳': 'ballot box vote election',
  '🗺': 'world map travel',
  // Symbols
  '❤️': 'red heart love romance',
  '🧡': 'orange heart love',
  '💛': 'yellow heart love',
  '💚': 'green heart love nature',
  '💙': 'blue heart love',
  '💜': 'purple heart love',
  '🖤': 'black heart love dark',
  '🤍': 'white heart love pure',
  '🤎': 'brown heart love',
  '💔': 'broken heart sad',
  '❣️': 'heart exclamation love',
  '💕': 'two hearts love',
  '💞': 'revolving hearts love',
  '💓': 'beating heart love',
  '💗': 'growing heart love',
  '💖': 'sparkling heart love',
  '💘': 'heart arrow love cupid',
  '💝': 'heart ribbon love gift',
  '💟': 'heart decoration love',
  '☮️': 'peace symbol',
  '✝️': 'cross christian religion',
  '☪️': 'star crescent muslim islam religion',
  '🕉': 'om hindu religion',
  '☯️': 'yin yang tao balance',
  '✡️': 'star of david jewish religion',
  '🔯': 'six pointed star',
  '🕎': 'menorah jewish religion',
  '☦️': 'orthodox cross religion',
  '⛎': 'ophiuchus zodiac',
  '♈': 'aries zodiac ram',
  '♉': 'taurus zodiac bull',
  '♊': 'gemini zodiac twins',
  '♋': 'cancer zodiac crab',
  '♌': 'leo zodiac lion',
  '♍': 'virgo zodiac',
  '♎': 'libra zodiac scales',
  '♏': 'scorpio zodiac scorpion',
  '♐': 'sagittarius zodiac archer',
  '♑': 'capricorn zodiac goat',
  '♒': 'aquarius zodiac water',
  '♓': 'pisces zodiac fish',
  '🆔': 'id card identity',
  '⚛️': 'atom science physics',
  '☢️': 'radioactive warning nuclear',
  '☣️': 'biohazard warning',
  '❌': 'cross mark error no wrong',
  '⭕': 'circle red',
  '⛔': 'no entry prohibited stop',
  '📛': 'name badge label',
  '🚫': 'prohibited no banned forbidden',
  '💯': 'hundred percent perfect score',
  '💢': 'anger symbol mad',
  '♨️': 'hot springs steam',
  '❗': 'exclamation mark important',
  '❕': 'white exclamation mark',
  '❓': 'question mark',
  '❔': 'white question mark',
  '‼️': 'double exclamation mark',
  '⁉️': 'exclamation question mark',
  '🔅': 'dim brightness low',
  '🔆': 'bright brightness high',
  '⚠️': 'warning caution alert',
  '🚸': 'children crossing caution',
  '🔱': 'trident emblem',
  '⚜️': 'fleur de lis emblem',
  '🔰': 'japanese beginner symbol',
  '♻️': 'recycle recycling green eco',
  '✔️': 'check mark done tick',
  '☑️': 'check box done',
  '🔴': 'red circle',
  '🟠': 'orange circle',
  '🟡': 'yellow circle',
  '🟢': 'green circle',
  '🔵': 'blue circle',
  '🟣': 'purple circle',
  '⚫': 'black circle',
  '⚪': 'white circle',
  '🟤': 'brown circle',
  '🔺': 'red triangle up',
  '🔻': 'red triangle down',
  '🔷': 'large blue diamond',
  '🔶': 'large orange diamond',
  '🔹': 'small blue diamond',
  '🔸': 'small orange diamond',
  '⬛': 'black large square',
  '⬜': 'white large square',
  '🟥': 'red square',
  '🟧': 'orange square',
  '🟨': 'yellow square',
  '🟩': 'green square',
  '🟦': 'blue square',
  '🟪': 'purple square',
  '🟫': 'brown square',
  '🔈': 'speaker low volume sound',
  '🔇': 'muted speaker silent no sound',
  '🔉': 'speaker medium volume sound',
  '🔊': 'loud speaker volume high sound',
  '🔔': 'bell notification alert ring',
  '🔕': 'bell slash muted silent',
  '♠️': 'spade suit cards black',
  '♣️': 'club suit cards black',
  '♥️': 'heart suit cards red',
  '♦️': 'diamond suit cards red',
  '🃏': 'joker card wild',
  '🀄': 'mahjong red dragon',
  '🎴': 'flower playing cards',
  '➕': 'plus add math',
  '➖': 'minus subtract math',
  '➗': 'divide division math',
  '✖️': 'multiply times math',
  '💲': 'dollar sign money currency',
  '💱': 'currency exchange money',
  '™️': 'trade mark registered brand',
  '©️': 'copyright',
  '®️': 'registered trademark',
  '🔀': 'shuffle random',
  '🔁': 'repeat loop',
  '🔂': 'repeat one loop',
  '🔄': 'counterclockwise arrows refresh',
  '▶️': 'play button start',
  '⏸': 'pause button',
  '⏹': 'stop button',
  '⏺': 'record button',
  '⏭': 'next track skip',
  '⏮': 'previous track',
  '⏩': 'fast forward',
  '⏪': 'rewind backward',
  '◀️': 'reverse back arrow',
  '🔼': 'upward button arrow up',
  '🔽': 'downward button arrow down',
  '➡️': 'right arrow',
  '⬅️': 'left arrow',
  '⬆️': 'up arrow',
  '⬇️': 'down arrow',
}

type Props = {
  onSelect: (emoji: string) => void
  onClose: () => void
  style?: React.CSSProperties
  inline?: boolean
  hideRemove?: boolean
}

export default function EmojiPicker({ onSelect, onClose, style, inline, hideRemove }: Props) {
  const [query, setQuery] = useState('')
  const [activeCategory, setActiveCategory] = useState(0)
  const inputRef = useRef<HTMLInputElement>(null)
  const scrollRef = useRef<HTMLDivElement>(null)

  useEffect(() => { inputRef.current?.focus() }, [])

  const filtered = useMemo(() => {
    if (!query.trim()) return null
    const q = query.toLowerCase()
    const seen = new Set<string>()
    return CATEGORIES.flatMap(c => c.emojis).filter(e => {
      if (seen.has(e)) return false
      seen.add(e)
      return (EMOJI_KW[e] ?? '').includes(q)
    })
  }, [query])

  function selectCategory(i: number) {
    setActiveCategory(i)
    setQuery('')
    scrollRef.current?.scrollTo({ top: 0, behavior: 'smooth' })
  }

  const displayEmojis = filtered ?? CATEGORIES[activeCategory]?.emojis ?? []

  if (inline) return (
    <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: '10px', width: '100%', overflow: 'hidden', ...style }}>
      <div style={{ padding: '8px', borderBottom: '1px solid var(--border)' }}>
        <input ref={inputRef} value={query} onChange={e => setQuery(e.target.value)}
          placeholder="Search emoji…"
          style={{ width: '100%', padding: '6px 10px', border: '1px solid var(--border)', borderRadius: '6px', fontSize: '13px', fontFamily: 'var(--font-sans)', outline: 'none', background: 'var(--sidebar-bg)', color: 'var(--text)', boxSizing: 'border-box' }} />
      </div>
      {!query && (
        <div style={{ display: 'flex', overflowX: 'auto', padding: '4px 6px', gap: '2px', borderBottom: '1px solid var(--border)', scrollbarWidth: 'none' }}>
          {CATEGORIES.map((cat, i) => (
            <button key={cat.label} onClick={() => selectCategory(i)} title={cat.label}
              style={{ flexShrink: 0, background: i === activeCategory ? 'var(--accent-light)' : 'none', border: 'none', borderRadius: '5px', padding: '4px 6px', fontSize: '16px', cursor: 'pointer', lineHeight: 1 }}>
              {cat.icon}
            </button>
          ))}
        </div>
      )}
      <div ref={scrollRef} style={{ display: 'flex', flexWrap: 'wrap', gap: '2px', padding: '8px', maxHeight: '180px', overflowY: 'auto' }}>
        {displayEmojis.length === 0
          ? <div style={{ width: '100%', textAlign: 'center', padding: '20px', fontSize: '13px', color: 'var(--text-tertiary)' }}>No results</div>
          : displayEmojis.map((em, i) => (
            <button key={i} onClick={() => onSelect(em)}
              style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: '20px', padding: '4px', borderRadius: '5px', lineHeight: 1 }}
              onMouseEnter={e => { (e.currentTarget as HTMLElement).style.background = 'var(--sidebar-hover)' }}
              onMouseLeave={e => { (e.currentTarget as HTMLElement).style.background = 'none' }}>
              {em}
            </button>
          ))}
      </div>
      {!hideRemove && (
        <div style={{ borderTop: '1px solid var(--border)', padding: '4px 8px' }}>
          <button onClick={() => onSelect('')}
            style={{ width: '100%', background: 'none', border: 'none', cursor: 'pointer', fontSize: '12px', color: 'var(--text-tertiary)', padding: '4px', borderRadius: '4px', fontFamily: 'var(--font-sans)' }}
            onMouseEnter={e => { (e.currentTarget as HTMLElement).style.background = 'var(--sidebar-hover)' }}
            onMouseLeave={e => { (e.currentTarget as HTMLElement).style.background = 'none' }}>
            Remove icon
          </button>
        </div>
      )}
    </div>
  )

  return (
    <>
      <div style={{ position: 'fixed', inset: 0, zIndex: 999 }} onClick={onClose} />
      <div onClick={e => e.stopPropagation()}
        style={{ position: 'absolute', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: '10px', boxShadow: 'var(--shadow-lg)', zIndex: 1000, width: '300px', overflow: 'hidden', ...style }}>
        {/* Search */}
        <div style={{ padding: '8px', borderBottom: '1px solid var(--border)' }}>
          <input ref={inputRef} value={query} onChange={e => setQuery(e.target.value)}
            placeholder="Search emoji…"
            style={{ width: '100%', padding: '6px 10px', border: '1px solid var(--border)', borderRadius: '6px', fontSize: '13px', fontFamily: 'var(--font-sans)', outline: 'none', background: 'var(--sidebar-bg)', color: 'var(--text)', boxSizing: 'border-box' }} />
        </div>

        {/* Category tabs */}
        {!query && (
          <div style={{ display: 'flex', overflowX: 'auto', padding: '4px 6px', gap: '2px', borderBottom: '1px solid var(--border)', scrollbarWidth: 'none' }}>
            {CATEGORIES.map((cat, i) => (
              <button key={cat.label} onClick={() => selectCategory(i)}
                title={cat.label}
                style={{ flexShrink: 0, background: i === activeCategory ? 'var(--accent-light)' : 'none', border: 'none', borderRadius: '5px', padding: '4px 6px', fontSize: '16px', cursor: 'pointer', lineHeight: 1 }}>
                {cat.icon}
              </button>
            ))}
          </div>
        )}

        {/* Grid */}
        <div ref={scrollRef} style={{ display: 'flex', flexWrap: 'wrap', gap: '2px', padding: '8px', maxHeight: '220px', overflowY: 'auto' }}>
          {displayEmojis.length === 0 ? (
            <div style={{ width: '100%', textAlign: 'center', padding: '20px', fontSize: '13px', color: 'var(--text-tertiary)' }}>No results</div>
          ) : displayEmojis.map((em, i) => (
            <button key={i} onClick={() => { onSelect(em); onClose() }}
              style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: '20px', padding: '4px', borderRadius: '5px', lineHeight: 1 }}
              onMouseEnter={e => { (e.currentTarget as HTMLElement).style.background = 'var(--sidebar-hover)' }}
              onMouseLeave={e => { (e.currentTarget as HTMLElement).style.background = 'none' }}>
              {em}
            </button>
          ))}
        </div>

        {/* Remove icon option */}
        {!hideRemove && <div style={{ borderTop: '1px solid var(--border)', padding: '4px 8px' }}>
          <button onClick={() => { onSelect(''); onClose() }}
            style={{ width: '100%', background: 'none', border: 'none', cursor: 'pointer', fontSize: '12px', color: 'var(--text-tertiary)', padding: '4px', borderRadius: '4px', fontFamily: 'var(--font-sans)' }}
            onMouseEnter={e => { (e.currentTarget as HTMLElement).style.background = 'var(--sidebar-hover)' }}
            onMouseLeave={e => { (e.currentTarget as HTMLElement).style.background = 'none' }}>
            Remove icon
          </button>
        </div>}
      </div>
    </>
  )
}
